spring:
  application:
    name: order-service
  
  profiles:
    active: kafka  # Default to Kafka, can be overridden with rabbitmq or pulsar
  
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  
  cloud:
    stream:
      bindings:
        orderEvents-out-0:
          destination: order-events
          content-type: application/json

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.poc: DEBUG
    org.springframework.cloud.stream: DEBUG

---
spring:
  config:
    activate:
      on-profile: kafka
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          default-broker-port: 9092

---
spring:
  config:
    activate:
      on-profile: rabbitmq
  cloud:
    stream:
      rabbit:
        binder:
          connection-name-prefix: order-service
        bindings:
          orderEvents-out-0:
            producer:
              routing-key-expression: headers['partitionKey']

---
spring:
  config:
    activate:
      on-profile: pulsar
  cloud:
    stream:
      pulsar:
        binder:
          service-url: pulsar://localhost:6650